---
- name: Installing apache2 and checking the url connectivity
  hosts: webservers
  tasks:
   - name: Installing apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: Copying content into /var/www/html/index.html
     copy:
      content: "Welcome to Ansible World"
      dest: /var/www/html/index.html
   - name: Restarting apache2
     service:
      name: apache2
      state: restarted
   - name: Checking URL response
     uri:
      url: http://10.10.10.93
      status: 200 

...
