---
- name: Implementing handlers 
  hosts: 10.10.10.94
  tasks:
   - name: Installing apache2
     apt: 
      name: apache2
      state: present
     notify:
      - url_response
   - name: Editing index.html file
     copy:
      content: "Welcome to Devops"
      dest: /var/www/html/index.html
     notify:
      - restart_apache2
  handlers:
   - name: restart_apache2
     service:
      name: apache2
      state: restarted
   - name: url_response
     uri:
      url: http://10.10.10.94
      status: 200


...
