---
- name: Creating playbook for installing apache2 using Playscope variables
  hosts: 10.10.10.93
  vars:
   - a: apache2
   - b: present
   - c: no 
  tasks:
   - name: Installing apache2 using Playscope variables or global scope variables
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"

# ansible-playbook playbook7.yml --extra-vars "a=tree b=present c=no" -b
#  ansible-playbook playbook7.yml -b #it will install apache2

...
