---
- name: Installing a package using when condition
  hosts: 10.10.10.94
  vars:
   - a: "10"
  tasks:
   - name: Installing tree
     apt: 
      name: tree
      state: present 
     when:
      a == "10"

#ansible-playbook playbook14.yml -b
#ansible-playbook playbook14.yml --extra-vars "a='20'" -b
#ansible-playbook playbook14.yml --extra-vars "a='10'" -b
...
