---
- name: Configuring apache2 using include module
  hosts: 10.10.10.95
  tasks:
   - include: "{{item}}"
     with_items:
      - install_apache2.yml
      - edit_index.html.yml
      - restart_apache2.yml
      - url_response.yml
...
