---
- name: Creating files or directories by using global scope variables
  hosts: all
  tasks:
   - name: Creating file or directory based on user input
     file:
      name: "{{a}}"
      state: "{{b}}"
      owner: "{{c}}"
      group: "{{d}}"
      mode: "{{e}}"
# ansible-playbook playbook6.yml --extra-vars "a=sai1 b=touch c=ubuntu d=ubuntu e=755" -b

#  ansible-playbook playbook6.yml --extra-vars "a=sai1 b=touch c=vagrant d=vagrant e=755" 
...
